  db:
    image: postgres:9.4
    volumes:
      - ./data:/var/lib/postgresql/data
    env_file:
      - ./odoo/.env
  odoo:
    #image: odoo:8
    image: jtb0/myodoov8
    links:
      - db
    volumes:
      - ./odoo/odoo:/var/lib/odoo
      - ./odoo/addons:/mnt/extra-addons
    environment:
      - VIRTUAL_HOST=odoo.${HOSTNAME}
      - VIRTUAL_PORT=8069
    ports:
      - "8069:8069"

  wordpress:
    build: ./wordpress
    links:
      - mariadb:mysql
    ports:
      - 8080:80
    environment:
      - WORDPRESS_DB_PASSWORD=swialyitt6
      - VIRTUAL_HOST=wp.${HOSTNAME}
      - VIRTUAL_PORT="80"
      - HTTP_METHOD=noredirect

  mariadb:
    image: mariadb
    environment:
      MYSQL_ROOT_PASSWORD: swialyitt6

  nginx-proxy:
    image: jwilder/nginx-proxy
    container_name: nginx-proxy
    ports:
      - "80:80"
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - ./nginx/conf/additional_proxy.conf:/etc/nginx/conf.d/additional_proxy.conf:ro
