version: "2"
services:
  wordpress:
    build: .
    links:
      - db:mysql
    ports:
      - 8080:80
    environment:
      - WORDPRESS_DB_PASSWORD=swialyitt6
      - VIRTUAL_HOST=wp.docki
      - VIRTUAL_PORT="80"
      - HTTP_METHOD=noredirect

  db:
    image: mariadb
    environment:
      MYSQL_ROOT_PASSWORD: swialyitt6
